{% set version = "0.1.7" %}

package:
  name: allennlp-optuna
  version: {{ version }}

source:
  url: https://github.com/himkt/allennlp-optuna/archive/v{{ version }}.tar.gz
  sha256: 65fd8038efbb1a43b8bfc2979a876367b833a734d1e1dd92ed613a103cf24295

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - allennlp >=2,<3
    - optuna >=2.6,<3

test:
  requires:
    - python {{ python_min }}
  imports:
    - allennlp_optuna

about:
  home: https://github.com/himkt/allennlp-optuna
  license: MIT
  license_file: LICENSE
  summary: AllenNLP plugin for adding subcommands to use Optuna, making hyperparameter optimization easy

  doc_url: https://allennlp-optuna.readthedocs.io/en/latest/
  dev_url: https://github.com/himkt/allennlp-optuna

extra:
  recipe-maintainers:
    - himkt
    - h-vetinari
